### ISSUE TITLE
Refactor filtering on homepage

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#552]
The filter.js is getting more and more complex.
Most of the work of this file should be done in the backend.

- [x] Move the build card function into it's own file
- [x] Removed unused code
- [x] Reduce duplication
- [x] Make sure naming makes sense
